### ISSUE TITLE
Is Time::Piece version 1.33 truly required

### ISSUE THREAD

**Issue by hightowe** [chazmcgarvey/File-KDBX#3]
kpcli unshifts ~/perl5/ paths into @INC in a BEGIN block to try to make life easier on folks who install local modules with tools like cpanm, but because Time::Piece is part of core Perl, it is loaded *very* early in the Perl bootstrapping process and therefore it is essentially impossible to override the system installed version of Time::Piece by altering @INC in a BEGIN block...

As such, on Linux Mint 19.3, which is based on Ubuntu 18.04 (and so still a supported LTS release), the only way to use a locally installed (~/perl5) version of File::KDBX is to set the environment variable PERL5LIB=/home/<user>/perl5/lib/perl5 prior to running perl, else **Time::Piece 1.31** (part of core Perl 5.26.1) is pulled in and then File::KDBX can't load, due to its stated dependency on **Time::Piece version 1.33**.

**Comment by chazmcgarvey** [comment]
Unless a different workaround can be put in place, Time::Piece 1.33 is necessary for only one thing: KDBX4 timestamps on 32-bit systems. There's no other reason to prereq it.

As you point out, Time::Piece could be loaded relatively early because it has many dependents (including maybe other core libraries).

But it isn't loaded automatically, so I think it must be possible to alter `@INC` at some point in your program that is early enough for Time::Piece to not be loaded. Could you add the BEGIN block before using any other module, or do you want core modules to be loaded from system rather than ~/perl5? (If so, is there a reason for this? Is loading core libraries from ~/perl5 considered a security issue?)

If you want to keep your BEGIN block after loading core modules, you could maybe use [Module::Loaded](https://perldoc.perl.org/Module::Loaded) to cause Time::Piece to be reloaded (after unshifting `@INC`), perhaps only if you detect that the Time::Piece version is too low.

What do you think?

**Comment by hightowe** [comment]
I moved the BEGIN block up and resolved the issue that way. Thanks for the reply.

**Comment by chazmcgarvey** [comment]
I do like the idea of not prereq'ing non-LTS modules, though. I will see if there's another workaround so that this prereq can be removed.
